Sys.setenv(PROJ_LIB = 'C:\\OSGeo4W64\\share\\proj')
Sys.setenv(GDAL_DATA = 'C:\\OSGeo4W64\\share\\gdal')
Sys.setenv(GDAL_DRIVER_PATH = 'C:\\OSGeo4W64\\bin\\gdalplugins')
Sys.setenv(PATH = paste0('C:\\OSGeo4W64\\bin;',Sys.getenv("PATH")))
options("rgdal_show_exportToProj4_warnings"="none")
# library(devtools)
# library(usethis)

# Sys.getenv('PATH')
# Sys.getenv('PROJ_LIB')
# Sys.getenv('GDAL_DATA')
# Sys.getenv('GDAL_DRIVER_PATH')
